// Full US + India ticker/company-name search, entirely client-side. Fetches
// the static ticker-index.json (generated by scripts/generate_ticker_index.py,
// ~158KB gzipped) once per page load and builds a first-letter prefix index
// from it — every search after that first fetch is a synchronous, zero-
// network, sub-millisecond lookup. This exists because round-tripping every
// keystroke to the backend meant search speed was at the mercy of Render's
// free-tier network/CPU latency (a real, user-visible problem — see the
// backend's data/search.py for the equivalent server-side indexing, kept
// around as a fallback API but no longer on the hot path for typing).

let entries = null; // [ticker, name, market][]
let prefixIndex = null; // Map<firstChar, entry[]>
let loadPromise = null;

function buildIndex(list) {
  const index = new Map();
  for (const entry of list) {
    const [ticker, name] = entry;
    const tUpper = ticker.toUpperCase();
    const nUpper = name.toUpperCase();
    const tChar = tUpper[0];
    const nChar = nUpper[0];
    if (tChar) {
      if (!index.has(tChar)) index.set(tChar, []);
      index.get(tChar).push([tUpper, nUpper, entry]);
    }
    if (nChar && nChar !== tChar) {
      if (!index.has(nChar)) index.set(nChar, []);
      index.get(nChar).push([tUpper, nUpper, entry]);
    }
  }
  return index;
}

// Kick off the fetch as early as possible (call once from App/SearchPage on
// mount) — by the time a user finishes typing their first couple of
// characters, this has almost always already resolved.
export function preloadTickerIndex() {
  if (loadPromise) return loadPromise;
  loadPromise = fetch("/ticker-index.json")
    .then((res) => {
      if (!res.ok) throw new Error(`ticker-index.json ${res.status}`);
      return res.json();
    })
    .then((list) => {
      entries = list;
      prefixIndex = buildIndex(list);
    })
    .catch(() => {
      // Best-effort — searchFullIndex() below just returns [] until/unless
      // this eventually succeeds (e.g. transient network hiccup); the
      // curated popularTickers.js list still covers common names either way.
    });
  return loadPromise;
}

export function isTickerIndexReady() {
  return prefixIndex !== null;
}

function score(query, ticker, name) {
  if (ticker === query) return 0;
  if (ticker.startsWith(query)) return 1;
  if (name.startsWith(query)) return 2;
  if (ticker.includes(query)) return 3;
  if (name.includes(query)) return 4;
  return null;
}

export function searchFullIndex(query, limit = 8) {
  if (!prefixIndex) return [];
  const q = query.trim().toUpperCase();
  if (!q) return [];

  const seen = new Set();
  const scored = [];
  const candidates = prefixIndex.get(q[0]) || [];
  for (const [ticker, name, original] of candidates) {
    const s = score(q, ticker, name);
    if (s === null) continue;
    const key = `${original[2]}-${ticker}`;
    if (seen.has(key)) continue;
    seen.add(key);
    scored.push([s, ticker.length, original]);
  }

  // The prefix-bucketed pass only catches matches at the very start of the
  // ticker or name (scores 0-2). Only fall back to a full substring scan
  // (scores 3-4) on the rare occasion that didn't already fill the limit.
  if (scored.length < limit && entries) {
    for (const original of entries) {
      const ticker = original[0].toUpperCase();
      const name = original[1].toUpperCase();
      const key = `${original[2]}-${ticker}`;
      if (seen.has(key)) continue;
      const s = score(q, ticker, name);
      if (s === null || s < 3) continue;
      seen.add(key);
      scored.push([s, ticker.length, original]);
    }
  }

  scored.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  return scored.slice(0, limit).map(([, , [ticker, name, market]]) => ({ ticker, name, market }));
}
